# Generated by Django 2.0.4 on 2018-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Chronical_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
    ]
